# Generated by Django 4.1.7 on 2023-03-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_vendor1',
            new_name='is_vendor',
        ),
    ]
